### PR TITLE
multi: bump lnd+lndclient compile time dependency

### PR DESCRIPTION
**Pull request by guggero**
This PR adds compile time compatibility with lnd 0.16.

#### Pull Request Checklist
- [ ] Update `MinLndVersion` if your PR uses new RPC methods or fields of `lnd`.

### CODE REVIEW

**Review by bhandras — APPROVED** [review]
LGTM :pray:

**Comment by bhandras** [comment]
Shall we also bump the minimum lnd version to 0.15.99?

**Comment by guggero** [comment]
> Shall we also bump the minimum lnd version to 0.15.99?

I don't think we added anything that requires runtime compatibility. So `lnd 0.15.4-beta` should be fine.

**Comment by bhandras** [comment]
Shall we merge this given rc1 is out?

**Review by bhandras — APPROVED** [review]
🚀 🚀

**Comment by guggero** [comment]
Integration test seems to be flaky, it did complete on my machine. Kicked it again, let's see.

**Review by positiveblue — APPROVED** [review]
The second commit says `v1.19.2` but we bump golang to `v1.19.4`

**Pull request merged**
